#!/usr/bin/perl -w
#eval '/usr/bin/env perl -w $0 ${1+"$@"}'
#if 0;	

#$Id: synsim,v 1.3 2003/04/07 13:23:04 wim Exp $

setpgrp(0,$$);

use strict;
use lib '.','..';
#use Simulation::Tools::SynSim;
use Simulation::Automate;

&synsim();
